name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test:
    name: Test (Node 20)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (if present)
        run: npm run build --if-present

      # Will not fail the job if there's no "test" script yet
      - name: Test (if present)
        run: npm test --if-present
